"""Stable column order for versioned TSV outputs."""

STUDY_COLUMNS = [
    "study_id",
    "bioproject",
    "publication_title",
    "doi",
    "pmid",
    "year",
    "project_title",
    "project_description",
    "country",
    "region",
    "institution",
    "cacao_species",
    "cacao_variety",
    "fermentation_type",
    "fermentation_container",
    "fermentation_duration_hours",
    "season",
    "amplicon_type",
    "marker",
    "region_16s",
    "forward_primer",
    "reverse_primer",
    "sequencing_platform",
    "sequencing_instrument",
    "paired_end",
    "total_runs",
    "number_samples",
    "estimated_fastq_bytes",
    "raw_data_available",
    "metadata_quality",
    "include",
    "exclusion_reason",
    "source",
    "retrieved_at_utc",
]

RUN_COLUMNS = [
    "study_id",
    "bioproject",
    "study_accession",
    "secondary_study_accession",
    "run_accession",
    "experiment_accession",
    "biosample",
    "secondary_sample_accession",
    "sample_alias",
    "sample_title",
    "sample_description",
    "experiment_title",
    "scientific_name",
    "tax_id",
    "library_strategy",
    "library_source",
    "library_selection",
    "library_layout",
    "sequencing_platform",
    "sequencing_instrument",
    "base_count",
    "read_count",
    "fastq_bytes",
    "fastq_ftp",
    "fastq_md5",
    "country",
    "collection_date",
    "cultivar",
    "isolation_source",
    "first_public",
    "last_updated",
    "marker_classification",
    "analysis_include",
    "exclusion_reason",
    "source",
]

SAMPLE_COLUMNS = [
    "study_id",
    "sample_id",
    "run_accession",
    "bioproject",
    "biosample",
    "sample_alias",
    "country",
    "location",
    "fermentation_batch",
    "fermentation_hours",
    "fermentation_duration_hours",
    "relative_time",
    "fermentation_stage",
    "season",
    "cacao_variety",
    "replicate",
    "sampling_stratum",
    "sequencing_platform",
    "sequencing_instrument",
    "marker",
    "region_16s",
    "time_source",
    "analysis_include",
    "exclusion_reason",
    "notes",
]

EXCLUSION_COLUMNS = [
    "entity_type",
    "entity_id",
    "study_id",
    "bioproject",
    "reason",
    "metric",
    "threshold",
    "decision",
    "source",
]

DISCOVERY_COLUMNS = [
    "search_id",
    "query",
    "bioproject",
    "project_title",
    "project_description",
    "registration_date",
    "project_data_type",
    "total_runs",
    "library_strategies",
    "library_selections",
    "library_layouts",
    "sequencing_instruments",
    "countries",
    "estimated_fastq_bytes",
    "bacterial_16s_signal",
    "temporal_signal",
    "preliminary_screen",
    "screening_reason",
    "already_configured",
    "source",
    "retrieved_at_utc",
]

PILOT_SELECTION_COLUMNS = [
    "selection_rank",
    "selected_as_pilot",
    "eligible_primary",
    "study_id",
    "bioproject",
    "study_include",
    "metadata_quality",
    "publication_linked",
    "primers_known",
    "paired_end",
    "raw_data_available",
    "candidate_runs",
    "fermentation_batches",
    "unique_timepoints",
    "timepoints_hours",
    "temporal_stages",
    "selected_fastq_bytes",
    "selected_fastq_mib",
    "eligibility_reason",
]

PILOT_MANIFEST_COLUMNS = [
    "pilot_order",
    "study_id",
    "bioproject",
    "sample_id",
    "run_accession",
    "fermentation_stage",
    "fermentation_hours",
    "relative_time",
    "fermentation_batch",
    "sampling_stratum",
    "library_layout",
    "sequencing_platform",
    "sequencing_instrument",
    "fastq_ftp",
    "fastq_md5",
    "fastq_bytes",
    "estimated_bytes_total",
    "selection_reason",
]

DOWNLOAD_VALIDATION_COLUMNS = [
    "study_id",
    "bioproject",
    "sample_id",
    "run_accession",
    "read_file",
    "source_url",
    "local_path",
    "expected_bytes",
    "observed_bytes",
    "expected_md5",
    "observed_md5",
    "status",
    "validated_at_utc",
    "git_commit",
    "python_version",
]

FASTQ_VALIDATION_COLUMNS = [
    "study_id",
    "bioproject",
    "sample_id",
    "run_accession",
    "read_file",
    "local_path",
    "compressed_bytes",
    "read_count",
    "base_count",
    "minimum_read_length",
    "maximum_read_length",
    "gzip_valid",
    "fastq_valid",
    "status",
    "validated_at_utc",
    "git_commit",
    "python_version",
]

TABLE_SCHEMAS = {
    "studies": STUDY_COLUMNS,
    "runs": RUN_COLUMNS,
    "samples": SAMPLE_COLUMNS,
    "exclusion_log": EXCLUSION_COLUMNS,
}
