"""Stable column order for versioned TSV outputs."""

STUDY_COLUMNS = [
    "study_id",
    "bioproject",
    "publication_title",
    "doi",
    "pmid",
    "year",
    "project_title",
    "project_description",
    "country",
    "region",
    "institution",
    "cacao_species",
    "cacao_variety",
    "fermentation_type",
    "fermentation_container",
    "fermentation_duration_hours",
    "season",
    "amplicon_type",
    "marker",
    "region_16s",
    "forward_primer",
    "reverse_primer",
    "sequencing_platform",
    "sequencing_instrument",
    "paired_end",
    "total_runs",
    "number_samples",
    "estimated_fastq_bytes",
    "raw_data_available",
    "metadata_quality",
    "include",
    "exclusion_reason",
    "source",
    "retrieved_at_utc",
]

RUN_COLUMNS = [
    "study_id",
    "bioproject",
    "study_accession",
    "secondary_study_accession",
    "run_accession",
    "experiment_accession",
    "biosample",
    "secondary_sample_accession",
    "sample_alias",
    "sample_title",
    "sample_description",
    "experiment_title",
    "scientific_name",
    "tax_id",
    "library_strategy",
    "library_source",
    "library_selection",
    "library_layout",
    "sequencing_platform",
    "sequencing_instrument",
    "base_count",
    "read_count",
    "fastq_bytes",
    "fastq_ftp",
    "fastq_md5",
    "country",
    "collection_date",
    "cultivar",
    "isolation_source",
    "first_public",
    "last_updated",
    "marker_classification",
    "analysis_include",
    "exclusion_reason",
    "source",
]

SAMPLE_COLUMNS = [
    "study_id",
    "sample_id",
    "run_accession",
    "bioproject",
    "biosample",
    "sample_alias",
    "country",
    "location",
    "fermentation_batch",
    "fermentation_hours",
    "fermentation_duration_hours",
    "relative_time",
    "fermentation_stage",
    "season",
    "cacao_variety",
    "replicate",
    "sampling_stratum",
    "sequencing_platform",
    "sequencing_instrument",
    "marker",
    "region_16s",
    "time_source",
    "analysis_include",
    "exclusion_reason",
    "notes",
]

EXCLUSION_COLUMNS = [
    "entity_type",
    "entity_id",
    "study_id",
    "bioproject",
    "reason",
    "metric",
    "threshold",
    "decision",
    "source",
]

TABLE_SCHEMAS = {
    "studies": STUDY_COLUMNS,
    "runs": RUN_COLUMNS,
    "samples": SAMPLE_COLUMNS,
    "exclusion_log": EXCLUSION_COLUMNS,
}
